# Generated by Django 5.1.6 on 2025-02-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
